node/consensus/ceremony/consensus_frames.go

When commitLongestPath is run in some circumstances, every other frame is skipped
{"level":"info","ts":1697346594.2224607,"caller":"ceremony/consensus_frames.go:1029","msg":"selecting leader"}
{"level":"info","ts":1697346594.645416,"caller":"ceremony/consensus_frames.go:618","msg":"searching from committed frame","frame_number":0}
{"level":"info","ts":1697346594.6454806,"caller":"ceremony/consensus_frames.go:635","msg":"ranging over candidates for frame","frame_number":0}
{"level":"info","ts":1697346594.9158735,"caller":"ceremony/consensus_frames.go:689","msg":"setting longest path cursor to frame","frame_number":1}
{"level":"info","ts":1697346594.916715,"caller":"ceremony/consensus_frames.go:696","msg":"adding candidate","frame_number":1} …

fix commitLongestPath off-by-one

---

README.md
node/main.go

Adds a CLI flag to print the peer id from a config file and then exit. Useful for finding the peer id of a running node.
Tested with the config file of node running the latest ceremony client.
Example usage from the `node/` directory: 
```
> GOEXPERIMENT=arenas go run ./... --peer-id
Peer ID: Qme5PeqPSNRAvgWYbKoW9yy8S9tUwx1RBGaJ4ByE1a4rnu
```

Add CLI flag to print peer id from config

---

node/app/db_console.go
node/consensus/ceremony/ceremony_data_clock_consensus_engine.go
node/consensus/ceremony/consensus_frames.go
node/consensus/ceremony/peer_messaging.go
node/consensus/consensus_engine.go
node/main.go

libp2p has some quirks related to peer info synchronization, including delays on address resolution. Our expectations didn't line up correctly with its behavior, and so there was cases where high frame peers could get stuck in a loop where their state (as other nodes see it) is wrong, can't be synced with, but might even top out the list, making it lead to long periods where syncs will fail for a node (waiting for others to catch up). This works around those expectations.

v1.2.2 - sneaky sync troubles

---

README.md
node/app/db_console.go
node/main.go

Adds a `-balance` flag to the CLI to print the confirmed token balance. Fixes #37 .
I refactored a bit to be able to reuse the DB console's implementation for fetching the token balance.
Example usage from the `node` directory: 
`GOEXPERIMENT=arenas go run ./... -balance`
Example output:
`Confirmed balance: 1234 QUIL`
I tested the command on a running node and also verified that the DB console starts and displays the correct balance after the change. 
I didn't test the path that depends on the value of the `grpcWarn` variable as I'm not sure how.

feat: add balance flag to CLI 

---

Dockerfile
docker-compose.yml

Adding both a `Dockerfile` and `docker-compose.yml`  files that allow you to easily create an image and run it.
```shell
docker build -t quilibrium -t quilibrium:1.2.5 .
docker compose up -d
```
Notes:
* a golang 1.20 base image, based on Alpine linux is used
* a docker volume is used for the `node/.config` folder (and this includes the nested `storage` subfolder)
* the p2p port 8336/udp is mapped to the host, all interfaces
* the gRPC and REST ports 8337/tcp and 8338/tcp are mapped to host, localhost interface only
In order to drop into a shell inside the container:
```shell
docker compose exec -it node sh
```
Future work:
* set defaults for `listenRESTMultiaddr` and `listenGrpcMultiaddr`
* add `HEALTHCHECK` to the image
* add monitoring related services (Prometheus, Grafana, etc) to the …

add basic Docker configuration

---

node/poor_mans_cd.sh

the current state of the `node/poor_mans_cd.sh` relies on global variables to track both main process id and any child process id using the method below
```sh
start_process() {
GOEXPERIMENT=arenas go run ./... &
process_pid=$!
child_process_pid=$(pgrep -P $process_pid) # this is always empty
}
```
the problem is child_process_id is always empty I assume due to race condition where child processes start after the `child_process_id` variable is initialized. This leads to the following error message upon a new update being issued and picked up by the script
`kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]`
Hence any child processes continue running, which leads to the client to loop between panicing and restarting.
- `git reset --hard …

fix poor_man_cd race conditions

---

docker-compose.yml
node/config/config.go

When writing a default `config.yml` look for a `DEFAULT_LISTEN_GRPC_MULTIADDR` env var and if set use it's value to set the initial `listenGRPCMultiaddr`.
Only if `DEFAULT_LISTEN_GRPC_MULTIADDR` is present then also `DEFAULT_LISTEN_REST_MULTIADDR` will be used to set `listenRestMultiaddr`.
This change will allow docker-compose.yml to set `listenGRPCMultiaddr` and `listenRestMultiaddr`.
Related docker compose PR: https://github.com/QuilibriumNetwork/ceremonyclient/pull/46

add env var based default addresses for RPC endpoints

---

node/poor_mans_cd.sh

basically `is_process_running` gets called immediately after `start_process` and attempting to get the pid from `is_process_running` using `ps -ef` command doesn't find it I assume race condition, so this fix reverts back the `start_process` and `is_process_running` to use global variable renamed to `main_process_id`
```
no processes running
Process started with PID 17658 and child PID 
Process crashed or stopped. Restarting...
Process started with PID 17666 and child PID 
```
```
no processes running
process started with PID 17915 and child PID 
```

another bug fix with poor_man_cd

---

DOCKER-README.md
docker-compose.yml

Currently Docker cannot be used to run Quilibrium. Adding warning and explanation.

add sysctl related warning

---

DOCKER-README.md
node/main.go

Currently, the console displays the balance as below:
```
Owned: 0  Unconfirmed: 0
```
With this PR, the output format for the balance flag will be aligned with the above format:
```
> go run ./... -balance
Owned balance: 0 QUIL
Unconfirmed balance: 0 QUIL
```

Print unconfirmed amount as well with balance flag

---

README.md

Add the snippet from Telegram to enable optional stats collection about the health of the network.

Add stats collection opt-in docs

---

DOCKER-README.md
Dockerfile
docker-compose.yml
node/config/config.go
node/main.go

- the `sysctl` changes can be applied on the host
- relax warnings
- better instructions for the host
- how to detect buffer size issues
- add git commit to image as a label
- updated build command sample to provide git commit
- add resource requirements
- docker compose is not enforcing them
- add default stats collection
- fix several config file permissions

better buffer instructions and other minor changes

---

.env.example
.gitignore
DOCKER-README.md
Dockerfile
Taskfile.yaml
docker-compose.yml

- switching to a multi stage Dockerfile
- build stage has golang
- installs the `node` binary
- installs the `grpcurl` tool
- the target stage based on [Alpine Linux](https://www.alpinelinux.org/)
- copies over the `node` and `grpcurl` binaries and a couple of json files
- much smaller image, 151MB vs 1.18GB
- safer since neither source code nor `go` are present in production
- adding [Taskfile](https://taskfile.dev/) task runner to help with building and running
- adding `healthcheck` to `docker-compose.yml`
-  `docker-compose.yml` can be customised through `.env`
- `.env.example` provided as a sample

multi stage Dockerfile and Taskfile

---

docker-compose.yml

When I deploy docker container today, I found volumes default value is not work in docker-compose.xml and node initialization likes a brand new one, so I entered the internal of container and found that node loaded a different path of config which is /opt/ceremonyclient/node/.config. Hope my information can help, thanks.

Modify the wrong default volumes value to /root/.config

---

.dockerignore

I utilize two configuration directories, `.config` and `.config2`, for creating two separate Docker containers. 
Currently, when building the Docker image, the process includes copying the `.config2` directory into the image.  So, the image size is extreme due to the `store` subdirectory within `.config2`.
With this PR, we exclude all the `.config` dirs.

Exclude multiple config dirs from Docker build

---

node/config/config.go

Adds two new bare metal bootstrap peers both with high end AMD cpus and 128GB ram. The first one is in the US and the second is in the EU. The first one is at Latitude and the second one is at an untested new provider.

Add new bootstrap peers

---

node/app/node.go
node/store/clock.go

This fixes a bug where:
* new installs panics on compaction
* existing installs that delete `.config/store` panics on compaction
* possibly other cases
To reproduce either:
* new node
* remove `.config/store`
I'm not sure if it is ok to just skip, but this is how I fixed here.

bugfix: skip compaction if missing data

---

node/main.go

Watching `-node-info` is a clean way to track the progress. I have fixed a small typo and added peer score to the command:
```
Every 2.0s: docker exec -it quilibrium-node1-1 node -node-info
Peer ID: <peer_id>
Version: 1.4.13
Max Frame: 119622
Peer Score: 0
Owned balance: 0 QUIL
Unconfirmed balance: 0 QUIL
```

Fixing print typo and adding peer score

---

node/config/config.go

This node will no longer run after 26/5, so want to remove it to avoid issues for others.

Remove bootstrap peer

---

client/cmd/crossMint.go
client/go.mod
client/go.sum
node/main.go

The node tries to create a self-test when ran with the `-dht-only` flag, but it doesn't load the KZG ceremony data in DHT-only mode which leads to a crash.
Don't run self-test when the `-dht-only` flag is set.
I tested by starting a node locally in default mode with and without existing self-test and with the `-dht-only` flag.

Don't run self-test in DHT-only mode

---

client/cmd/root.go

`qclient` by default expects the config folder under `../node/.config/` which is not working when the binary is run from PATH.
The workaround is to run the command like:
```shell
qclient <sub-command> --config .config <args>
```
This PR fixes the config loading to default it to `.config/` (that is `.config/` under current folder).
Related issue: https://github.com/QuilibriumNetwork/ceremonyclient/issues/175

shift default config directory of qclient under current folder

---

docker-compose.yml

Change volume mapping so .config folder is created inside node folder and not on root folder.

Fix docker-compose volume mapping for .config folder

---

node/main.go

Q logo is not appearing correctly on the terminal while running node. Printing a new line character after "Signature check passed" will fix it

Update main.go to fix Q logo in cli

---

node/release_autorun.sh

There is no `$arch` variable to identify the architecture, `uname -m` should be used to determine the architecture.

fix arm64 architecture error

---

node/crypto/wesolowski_frame_prover.go
node/crypto/wesolowski_frame_prover_test.go

There was a redundant check for if the increment was over 800k. 
This would be redundant due to the first check of "if the difficulty was under 25k" would be met at anything over 700k.
Moved to a function, due to it being used twice (in the Calculating and Verifying of the Proof) and to be able to add tests.

Remove extra difficulty check for proofs
